= Network

The protocol is an adaptation of https://github.com/JanKlopper/pixelvloed/blob/master/protocol.md

To be compatible with the _"pixelvloed"_ Protocol, LedWall packets start at _protocol_ number `0x10`

WARNING: The Packet-Size is reduced to 128 Bytes.

== Protocols

=== Protocol `0x10`

Non-destructive Stream of Pixels with 8bit coordinates. The Pixel Stream replaces individual Pixels, the remaining _image_ is retained.

|===
| Byte | Contents

| 0
| 0x10 _protocol_

| 1
| protocol settings

| 2
| 8bit *x*-coordinate

| 3
| 8bit *y*-coordinate

| 4
| 8bit red color value

| 5
| 8bit green color value

| 6
| 8bit blue color value
|===

=== Protocol `0x1x`

Stream of Pixels, Quad-Tree compression

=== Protocol `0x1x`

Clear screen / set all pixels to provided color

=== Protocol `0x1a`

Multi-Frame Bitmap, 1st Frame is full, following Frames only have the difference to the previous _constructed_ frame.

One Frame can have a Maximum of 256 Pixels. If a Bitmap should have more than 256 Pixels it has to be constructed of multiple Frames.

.Delay between Frames
      0 => no frame delay -> used to compose Bitmaps with more than 256 Pixels
  1-100 => ms        (   0 -   100 ms)
101-150 => ms *   10 (  10 -   500 ms)
151-200 => ms *  500 ( 500 - 25000 ms)
201-250 => ms * 1000 (1000 - 50000 ms)

----
0x1a // header - protocol
0x00 // header - options
0x00 // delay before frame
0x01 // number of pixels in frame
0x00 // x
0x00 // y
0xff // red
0x00 // green
0x00 // blue
0x00 // delay before frame
0x02 // number of pixels in frame
...  // 2 pixels x 5 byte
...  // delay before frame
...  // number of pixels in frame
...  // count pixels x 5 byte
----

