#ifndef LEDWALL_EVENTS_H
#define LEDWALL_EVENTS_H

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(LEDWALL_EVENTS);

enum {
    LEDWALL_EVENT_POWER_CHANGED,        // arg: (bool) isPowered
    LEDWALL_EVENT_BRIGHTNESS_CHANGED,   // arg: (uint8_t) brightness
    LEDWALL_EVENT_MODE_CHANGED,         // arg: (int) modeIndex
    LEDWALL_EVENT_MODE_OPTIONS_CHANGED, // arg: NONE

    LEDWALL_BTN_EVENT_POWER,
    LEDWALL_BTN_EVENT_PRESET_NEXT,
    LEDWALL_BTN_EVENT_TOGGLE_PRESET_AUTO_CHANGE,
};

#endif //LEDWALL_EVENTS_H
